name: Build Windows packages

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      runs-on:
        required: true
        type: string
    secrets:
      AZURE_TENANT_ID:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_SIGNING_ENDPOINT:
        required: true
      AZURE_SIGNING_ACCOUNT:
        required: true
      AZURE_SIGNING_CERTIFICATE_NAME:
        required: true

permissions:
  contents: read

env:
  WINSPARKLE_ED_KEY: ${{ vars.WINSPARKLE_ED_KEY }}
  WINSPARKLE_AUTHENTICODE_ORG: ${{ vars.WINSPARKLE_AUTHENTICODE_ORG }}

jobs:
  build-1:
    uses: ./.github/workflows/build-stage.yml
    secrets: inherit
    with:
      arch: ${{ inputs.arch }}
      runs-on: ${{ inputs.runs-on }}
      from-artifact: false

  build-2:
    needs: build-1
    if: needs.build-1.outputs.finished == 'false'
    uses: ./.github/workflows/build-stage.yml
    secrets: inherit
    with:
      arch: ${{ inputs.arch }}
      runs-on: ${{ inputs.runs-on }}
      from-artifact: true

  build-3:
    needs: build-2
    if: needs.build-2.outputs.finished == 'false'
    uses: ./.github/workflows/build-stage.yml
    secrets: inherit
    with:
      arch: ${{ inputs.arch }}
      runs-on: ${{ inputs.runs-on }}
      from-artifact: true

  build-4:
    needs: build-3
    if: needs.build-3.outputs.finished == 'false'
    uses: ./.github/workflows/build-stage.yml
    secrets: inherit
    with:
      arch: ${{ inputs.arch }}
      runs-on: ${{ inputs.runs-on }}
      from-artifact: true

  build-5:
    needs: build-4
    if: needs.build-4.outputs.finished == 'false'
    uses: ./.github/workflows/build-stage.yml
    secrets: inherit
    with:
      arch: ${{ inputs.arch }}
      runs-on: ${{ inputs.runs-on }}
      from-artifact: true

  build-6:
    needs: build-5
    if: needs.build-5.outputs.finished == 'false'
    uses: ./.github/workflows/build-stage.yml
    secrets: inherit
    with:
      arch: ${{ inputs.arch }}
      runs-on: ${{ inputs.runs-on }}
      from-artifact: true

  build-7:
    needs: build-6
    if: needs.build-6.outputs.finished == 'false'
    uses: ./.github/workflows/build-stage.yml
    secrets: inherit
    with:
      arch: ${{ inputs.arch }}
      runs-on: ${{ inputs.runs-on }}
      from-artifact: true

  build-8:
    needs: build-7
    if: needs.build-7.outputs.finished == 'false'
    uses: ./.github/workflows/build-stage.yml
    secrets: inherit
    with:
      arch: ${{ inputs.arch }}
      runs-on: ${{ inputs.runs-on }}
      from-artifact: true

  build-9:
    needs: build-8
    if: needs.build-8.outputs.finished == 'false'
    uses: ./.github/workflows/build-stage.yml
    secrets: inherit
    with:
      arch: ${{ inputs.arch }}
      runs-on: ${{ inputs.runs-on }}
      from-artifact: true

  build-10:
    needs: build-9
    if: needs.build-9.outputs.finished == 'false'
    uses: ./.github/workflows/build-stage.yml
    secrets: inherit
    with:
      arch: ${{ inputs.arch }}
      runs-on: ${{ inputs.runs-on }}
      from-artifact: true

  build-11:
    needs: build-10
    if: needs.build-10.outputs.finished == 'false'
    uses: ./.github/workflows/build-stage.yml
    secrets: inherit
    with:
      arch: ${{ inputs.arch }}
      runs-on: ${{ inputs.runs-on }}
      from-artifact: true

  build-12:
    needs: build-11
    if: needs.build-11.outputs.finished == 'false'
    uses: ./.github/workflows/build-stage.yml
    secrets: inherit
    with:
      arch: ${{ inputs.arch }}
      runs-on: ${{ inputs.runs-on }}
      from-artifact: true

  build-13:
    needs: build-12
    if: needs.build-12.outputs.finished == 'false'
    uses: ./.github/workflows/build-stage.yml
    secrets: inherit
    with:
      arch: ${{ inputs.arch }}
      runs-on: ${{ inputs.runs-on }}
      from-artifact: true

  build-14:
    needs: build-13
    if: needs.build-13.outputs.finished == 'false'
    uses: ./.github/workflows/build-stage.yml
    secrets: inherit
    with:
      arch: ${{ inputs.arch }}
      runs-on: ${{ inputs.runs-on }}
      from-artifact: true

  build-15:
    needs: build-14
    if: needs.build-14.outputs.finished == 'false'
    uses: ./.github/workflows/build-stage.yml
    secrets: inherit
    with:
      arch: ${{ inputs.arch }}
      runs-on: ${{ inputs.runs-on }}
      from-artifact: true

  package:
    needs: [build-1, build-2, build-3, build-4, build-5, build-6, build-7, build-8, build-9, build-10, build-11, build-12, build-13, build-14, build-15]
    if: ${{ !cancelled() && !failure() && join(needs.*.outputs.version, '') == '' }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/prepare-environment
      - uses: ./.github/actions/package
        id: package
        with:
          arch: ${{ inputs.arch }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          azure-signing-endpoint: ${{ secrets.AZURE_SIGNING_ENDPOINT }}
          azure-signing-account: ${{ secrets.AZURE_SIGNING_ACCOUNT }}
          azure-signing-certificate-name: ${{ secrets.AZURE_SIGNING_CERTIFICATE_NAME }}
