# Everything that's downloaded after cloning Chromium goes here.
# It will not work from main downloads.ini
[search_engines_data]
version = 202609082320
url = https://github.com/imputnet/helium-nonfree-assets/releases/download/%(version)s/nonfree-search-engines-data-%(version)s.tar.gz
download_filename = nonfree-search-engines-data-%(version)s.tar.gz
sha256 = 2a8d63af41454446d64bb5f19786d908419265f152adaff087132d8e0cda51a7
output_path = ./third_party/search_engines_data/resources_internal

[onboarding]
version = 202609160835
url = https://github.com/imputnet/helium-onboarding/releases/download/%(version)s/helium-onboarding-%(version)s.tar.gz
download_filename = onboarding-page-%(version)s.tar.gz
sha256 = 35ce782dc9534b5bff59af7937f22c90179ca9610883acb2e0d698cc6f799366
output_path = ./components/helium_onboarding

# If you are bumping this, you *NEED* to re-strip the assets.json
# file *every time* by using `devutils/clear-ublock-assets.js`.
[ublock_origin]
version = 1.75.0
url = https://github.com/imputnet/uBlock/releases/download/%(version)s/uBlock0_%(version)s.chromium.zip
sha256 = 49214674f7c6c474e60da647c05bd28463b1f7a55b2a2b0a53e9d297ef7bf3c6
download_filename = ublock-origin-%(version)s.zip
output_path = third_party/ublock
strip_leading_dirs = uBlock0.chromium
