name: 'Stage'
description: 'Stage build'
inputs:
  from_artifact:
    description: If a previous stage already uploaded build artifacts, the stage will resume building
    required: true
  package_here:
    description: Package on this runner if compilation finishes with time to spare
    default: false
  save_artifact:
    description: Save the build tree for another job
    default: true
  arm:
    description: Build arm binary
    required: false
    default: false
  upload_final:
    description: Upload artifacts after installer creation and signing
    required: false
    default: false
  final_directory:
    description: Directory of verified release artifacts to upload
    required: false
outputs:
  finished:
    description: If a previous stage already finished the build, the stage will set all output variables to the input ones and exit
  package_here:
    description: Compilation finished with enough time to package on this runner
  artifact_id:
    description: id of the build dir artifact
  version:
    description: version of the helium release we just built

runs:
  using: 'node24'
  main: 'index.js'
